#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────
# Beachhead Installer
# Self-hosted deployment platform
# ──────────────────────────────────────────────

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}▸${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
fail()  { echo -e "${RED}✗${NC} $1"; exit 1; }

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  ⚓  Beachhead Installer${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ── Check prerequisites ──────────────────────

info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  fail "Docker is not installed. Install it first: https://docs.docker.com/engine/install/"
fi
ok "Docker found: $(docker --version)"

if ! docker compose version &>/dev/null; then
  fail "Docker Compose V2 is not available. Update Docker or install the compose plugin."
fi
ok "Docker Compose found: $(docker compose version --short)"

if ! command -v git &>/dev/null; then
  fail "Git is not installed."
fi
ok "Git found: $(git --version)"

# Check Docker daemon is running
if ! docker info &>/dev/null; then
  fail "Docker daemon is not running. Start it and try again."
fi
ok "Docker daemon is running"

echo ""

# ── Prompt for configuration ─────────────────

echo -e "${BOLD}Configuration${NC}"
echo ""

# Domain
read -rp "$(echo -e "${CYAN}▸${NC}") Enter your domain name (e.g. deploy.example.com): " BEACHHEAD_DOMAIN
if [[ -z "$BEACHHEAD_DOMAIN" ]]; then
  fail "Domain name is required."
fi

# Validate domain format (basic check)
if ! echo "$BEACHHEAD_DOMAIN" | grep -qP '^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)+$'; then
  # fallback for macOS (no -P flag)
  if ! echo "$BEACHHEAD_DOMAIN" | grep -qE '^[a-zA-Z0-9][a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'; then
    warn "Domain '${BEACHHEAD_DOMAIN}' may not be valid. Continuing anyway."
  fi
fi

# Email for LetsEncrypt
read -rp "$(echo -e "${CYAN}▸${NC}") Email for SSL certificates (LetsEncrypt): " LETSENCRYPT_EMAIL
if [[ -z "$LETSENCRYPT_EMAIL" ]]; then
  fail "Email is required for LetsEncrypt SSL certificates."
fi

# Database password
DB_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | head -c 32)
info "Generated secure database password"

# GitHub webhook secret (optional)
echo ""
read -rp "$(echo -e "${CYAN}▸${NC}") Default GitHub webhook secret (leave blank to skip): " GITHUB_WEBHOOK_SECRET
GITHUB_WEBHOOK_SECRET="${GITHUB_WEBHOOK_SECRET:-}"

echo ""
echo -e "${BOLD}Summary${NC}"
echo "  Domain:    ${BEACHHEAD_DOMAIN}"
echo "  Email:     ${LETSENCRYPT_EMAIL}"
echo "  Webhook:   ${GITHUB_WEBHOOK_SECRET:-<not set>}"
echo ""
read -rp "$(echo -e "${CYAN}▸${NC}") Proceed with installation? [Y/n] " CONFIRM
CONFIRM="${CONFIRM:-Y}"
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
  echo "Aborted."
  exit 0
fi

echo ""

# ── Write .env ───────────────────────────────

info "Writing .env configuration..."

cat > .env <<EOF
# Beachhead Configuration — generated by install.sh
NODE_ENV=production
PORT=3000

# Domain
BEACHHEAD_DOMAIN=${BEACHHEAD_DOMAIN}

# SSL
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

# Database
POSTGRES_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://beachhead:${DB_PASSWORD}@beachhead-db:5432/beachhead

# Auth (empty = bootstrap mode — no auth required)
AUTH_JWKS_URL=
AUTH_ISSUER=

# GitHub
GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}

# Deployment
DEPLOY_BASE_DIR=/var/beachhead/deployments
DOCKER_NETWORK=beachhead-net

# Health Check
HEALTH_CHECK_TIMEOUT=30000
HEALTH_CHECK_INTERVAL=2000
EOF

ok ".env written"

# ── Create Docker network ────────────────────

info "Ensuring beachhead-net Docker network exists..."
if docker network inspect beachhead-net &>/dev/null; then
  ok "Network beachhead-net already exists"
else
  docker network create beachhead-net
  ok "Created network beachhead-net"
fi

# ── Build dashboard ──────────────────────────

if command -v node &>/dev/null && [[ -d "dashboard" ]]; then
  info "Building dashboard..."
  (cd dashboard && npm install --silent && npm run build --silent) 2>&1 | tail -3
  ok "Dashboard built"
else
  warn "Node.js not found locally — dashboard will be built inside Docker"
fi

# ── Start services ───────────────────────────

info "Building and starting Beachhead..."
docker compose up -d --build 2>&1 | tail -10

echo ""

# ── Wait for health ──────────────────────────

info "Waiting for Beachhead API to become healthy..."
RETRIES=30
until curl -sf http://localhost:3000/api/health &>/dev/null || [[ $RETRIES -eq 0 ]]; do
  sleep 2
  RETRIES=$((RETRIES - 1))
done

if [[ $RETRIES -gt 0 ]]; then
  ok "Beachhead API is healthy"
else
  warn "API did not respond within 60s — it may still be starting. Check: docker compose logs beachhead"
fi

# ── Done ─────────────────────────────────────

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}${BOLD}  ⚓  Beachhead is running!${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  Dashboard:   ${BOLD}https://${BEACHHEAD_DOMAIN}${NC}"
echo -e "  API:         ${BOLD}https://${BEACHHEAD_DOMAIN}/api/health${NC}"
echo -e "  Webhook URL: ${BOLD}https://${BEACHHEAD_DOMAIN}/api/webhooks/github${NC}"
echo ""
echo -e "  ${YELLOW}Note:${NC} DNS for ${BEACHHEAD_DOMAIN} must point to this server's IP."
echo -e "  ${YELLOW}Note:${NC} SSL certificates will be provisioned automatically once DNS resolves."
echo ""
echo -e "  Useful commands:"
echo -e "    docker compose logs -f beachhead     ${CYAN}# API logs${NC}"
echo -e "    docker compose logs -f nginx-proxy   ${CYAN}# Proxy logs${NC}"
echo -e "    docker compose ps                    ${CYAN}# Service status${NC}"
echo -e "    docker compose down                  ${CYAN}# Stop everything${NC}"
echo ""
